#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
			commit system
	EOF
fi

uci -q set luci.main.socket="/var/run/ubus.sock"
uci -q commit luci

#if ! uci -q get system.@imm_init[0].anon_mount > "/dev/null"; then
#	uci -q set fstab.@global[0].anon_mount="1"
#	uci -q commit fstab

#	uci -q set system.@imm_init[0].anon_mount="1"
#	uci -q commit system
#fi

ln -sf "/sbin/ip" "/usr/bin/ip"

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

rm -rf "/tmp/luci-modulecache"
rm -f "/tmp/luci-indexcache"

exit 0
